name: sprawozdanie_yml
on: push
jobs:
  pdf_convert:
    runs-on: ubuntu-22.04
    steps:
      - run: sudo apt-get install texlive-xetex inkscape pandoc
      - uses: actions/checkout@v4
      - run: pip install ipykernel nbconvert matplotlib numpy pint open-atmos-jupyter-utils scipy PyMPDATA pandas
      - run: python -m nbconvert --to pdf --execute sprawozdanie_.ipynb
      - run: python get_gif.py
      - uses: actions/upload-artifact@v4
        with:
          path: out1.gif
      - uses: actions/upload-artifact@v4
        with:
          path: out2.gif
      - uses: actions/upload-artifact@v4
        with:
          path: out3.gif
      - uses: actions/upload-artifact@v4
        with:
          path: out4.gif
      - uses: actions/upload-artifact@v4
        with:
          path: out0.gif
      - uses: actions/upload-artifact@v4
        with:
          path: vh.gif
      - uses: actions/upload-artifact@v4
        with:
          path: sprawozdanie_.pdf
